AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for creating an RDS instance

Parameters:
  DBInstanceClass:
    Type: String
    Default: db.t2.micro
    Description: RDS instance class
  DBName:
    Type: String
    Default: mydatabase
    Description: Name of the database
  DBUsername:
    Type: String
    NoEcho: true
    Description: Username for the database
  DBPassword:
    Type: String
    NoEcho: true
    Description: Password for the database
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID in which to create the RDS instance
  SecurityGroupIds:
    Type: AWS::EC2::SecurityGroup::Id
    Description: List of security group IDs to associate with the RDS instance
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: List of subnet IDs to associate with the RDS instance
  EnvironmentName:
    Description: SDLC Environment Value e.g dev/qa/prod.
    Type: String

Resources:

  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for the RDS instance
      SubnetIds: !Ref SubnetIds

  RDSDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 10
      DBInstanceClass: !Ref DBInstanceClass
      Engine: mysql
      EngineVersion: '8.0.33'
      DBName: !Ref DBName
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      VPCSecurityGroups:
        - !Ref SecurityGroupIds
      DBSubnetGroupName: !Ref RDSSubnetGroup
      PubliclyAccessible: No

Outputs:
  RDSEndpoint:
    Value: !GetAtt RDSDatabase.Endpoint.Address
    Description: Endpoint of the RDS database
    Export:
      Name: !Sub "${AWS::StackName}-RDSEndpoint"
